App
using App::CommandSet = std::unordered_map<std::string, std::shared_ptr<commands::CommandConstructor>>
peka2tv::Peka2tvSIOClient::EventHubPtr App::msgSource
Referenced by ~App.
storage::Storage* App::storage
Referenced by CanExecute, HandleMessage.
peka2tv::Peka2tvHttpClient* App::httpClient
Referenced by HandleMessage.
std::ofstream App::logFile
Referenced by HandleMessage, ~App.
UserCache App::userCache
Referenced by CanExecute.
AppApi App::appApi
Referenced by HandleMessage.
std::unique_ptr<commands::Phase> App::phase
Referenced by HandleMessage, SetPhase.
App::App(peka2tv::Peka2tvSIOClient::EventHubPtr msgSource, storage::Storage *storage, peka2tv::Peka2tvHttpClient *httpClient)
References HandleMessage.
App::~App()
References logFile, msgSource.
void App::HandleMessage(const peka2tv::Peka2tvSIOClient::ChatMessage &x)
References appApi, CanExecute, ExtractCommand, httpClient, IsCommand, peka2tv::LogChatCommands, logFile, phase, storage, peka2tv::Peka2tvSIOClient::ChatMessage::text.
Referenced by App.
void App::SetPhase()
References phase.
Referenced by Main.
bool App::CanExecute(const peka2tv::Peka2tvSIOClient::ChatMessage &x)
References peka2tv::Peka2tvSIOClient::ChatMessage::from, UserCache::Get, peka2tv::Peka2tvSIOClient::ChatMessage::User::id, storage::models::user::Ignored, UserCache::Insert, IsOwner, storage, userCache.
Referenced by HandleMessage.
bool App::IsOwner(const peka2tv::Peka2tvSIOClient::ChatMessage &msg)
References peka2tv::Peka2tvSIOClient::ChatMessage::channel, peka2tv::Peka2tvSIOClient::ChatMessage::from, peka2tv::Peka2tvSIOClient::ChatMessage::User::id.
Referenced by CanExecute.
bool App::IsCommand(const std::string &msg)
Referenced by HandleMessage.
std::string App::ExtractCommand(const std::string &msg)
Referenced by HandleMessage.