peka2tv::Peka2tvSIOClient
using peka2tv::Peka2tvSIOClient::ms = int
using peka2tv::Peka2tvSIOClient::EventHub = boost::signals2::signal<void(const ChatMessage&)>
using peka2tv::Peka2tvSIOClient::EventHubPtr = std::shared_ptr<EventHub>
std::string peka2tv::Peka2tvSIOClient::host
Referenced by Connect.
sio::client peka2tv::Peka2tvSIOClient::client
Referenced by Connect, Join, Leave, ~Peka2tvSIOClient.
bool peka2tv::Peka2tvSIOClient::isChatListen
Referenced by Join.
std::unordered_map<std::string, std::weak_ptr<EventHub> > peka2tv::Peka2tvSIOClient::chatListeners
Referenced by Join, OnMessage.
std::vector<std::weak_ptr<EventHub> > peka2tv::Peka2tvSIOClient::allChatListeners
Referenced by Join, OnMessage, RemoveDanglingListeners.
void peka2tv::Peka2tvSIOClient::Connect(std::string host="http://chat.sc2tv.ru/")
References client, host.
Referenced by Main.
Peka2tvSIOClient::EventHubPtr peka2tv::Peka2tvSIOClient::Join(std::string channel)
References allChatListeners, chatListeners, client, isChatListen, OnMessage.
void peka2tv::Peka2tvSIOClient::Leave(std::string channel)
References client.
Referenced by OnMessage.
peka2tv::Peka2tvSIOClient::~Peka2tvSIOClient()
References client.
void peka2tv::Peka2tvSIOClient::OnMessage(sio::event &e)
References allChatListeners, chatListeners, Leave, ParseChatMessage, RemoveDanglingListeners.
Referenced by Join.
void peka2tv::Peka2tvSIOClient::RemoveDanglingListeners()
References allChatListeners.
Referenced by OnMessage.
Peka2tvSIOClient::ChatMessage peka2tv::Peka2tvSIOClient::ParseChatMessage(std::map< std::string, sio::message::ptr > &obj)
References peka2tv::Peka2tvSIOClient::ChatMessage::anonymous, peka2tv::Peka2tvSIOClient::ChatMessage::channel, peka2tv::Peka2tvSIOClient::ChatMessage::User::color, peka2tv::Peka2tvSIOClient::ChatMessage::from, peka2tv::Peka2tvSIOClient::ChatMessage::User::id, peka2tv::Peka2tvSIOClient::ChatMessage::User::name, peka2tv::Peka2tvSIOClient::ChatMessage::text, peka2tv::Peka2tvSIOClient::ChatMessage::timestamp, peka2tv::Peka2tvSIOClient::ChatMessage::to.
Referenced by OnMessage.