AppApi
using AppApi::User = storage::models::user::User
UserCache* AppApi::userCache
Referenced by FindUser, UpdateUser.
storage::Storage* AppApi::storage
Referenced by FindUser, UpdateUser.
peka2tv::Peka2tvHttpClient* AppApi::httpClient
Referenced by FindUser.
AppApi::AppApi(UserCache *userCache, storage::Storage *storage, peka2tv::Peka2tvHttpClient *httpClient)
std::optional<User> AppApi::FindUser(UserInfoMember m, T val)
References peka2tv::Peka2tvHttpClient::FetchUserInfo, UserCache::Get, httpClient, storage::models::user::User::id, UserCache::Insert, storage, userCache, storage::models::user::Viewer.
Referenced by commands::Unban::Execute, commands::Ban::Execute.
void AppApi::UpdateUser(const User &u)
References UserCache::Get, storage::models::user::User::id, UserCache::Insert, storage, userCache.
Referenced by commands::Unban::Execute, commands::Ban::Execute.