commands::Phase
using commands::Phase::CommandSet = std::unordered_map<std::string, std::shared_ptr<commands::CommandConstructor>>
CommandSet commands::Phase::basicCommands
Referenced by mergeCommands.
commands::Phase::Phase()
virtual commands::Phase::~Phase()=default
virtual const CommandSet& commands::Phase::GetCommands()=0
void commands::Phase::mergeCommands(CommandSet &cs)
References basicCommands.
Referenced by commands::MoviePhase::MoviePhase, commands::SkipPhase::SkipPhase, commands::VotePhase::VotePhase.
void commands::Phase::SetPhase()