UserCache
using UserCache::User = storage::models::user::User
using UserCache::UserPtr = std::shared_ptr<User>
using UserCache::LRU = std::list<std::shared_ptr<User>>
size_t UserCache::capacity
Referenced by Insert.
boost::multi_index_container< UserInfoIndex, boost::multi_index::indexed_by< boost::multi_index::hashed_unique<boost::multi_index::const_mem_fun<UserInfoIndex, uint64_t, &UserInfoIndex::Id> >, boost::multi_index::hashed_unique<boost::multi_index::const_mem_fun<UserInfoIndex, std::string, &UserInfoIndex::Name>, NameHash, NameComp> > > UserCache::index
Referenced by Get, Insert.
LRU UserCache::lru
Referenced by Get, Insert.
UserCache::UserCache(size_t capacity)
void UserCache::Insert(const User &val)
References capacity, Get, index, lru.
Referenced by App::CanExecute, AppApi::FindUser, AppApi::UpdateUser.
UserCache::UserPtr UserCache::Get(uint64_t id)
References index, lru.
Referenced by App::CanExecute, AppApi::FindUser, Insert, AppApi::UpdateUser.
UserCache::UserPtr UserCache::Get(std::string name)
References index, lru.